# Generated by Django 3.2.6 on 2022-06-19 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Unit', 'Unit'), ('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Bag', 'Bag'), ('Crate', 'Crate'), ('Kongo', 'Kongo'), ('Carton', 'Carton')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('qty_remain', models.PositiveIntegerField(blank=True, default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price_per_one', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('seller_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock'),
        ),
    ]
