# Generated by Django 3.2.6 on 2022-06-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='buyer_name',
        ),
    ]
