# Generated by Django 3.2.6 on 2022-06-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_sale_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='buyer_name2',
            new_name='buyer_name',
        ),
    ]
