# Generated by Django 3.2.6 on 2022-06-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_buyer_name2_sale_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='buyer_name',
            new_name='buyer',
        ),
    ]
