# Generated by Django 3.2.6 on 2022-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220623_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
