# Generated by Django 3.2.6 on 2022-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.CharField(blank=True, default='Omotosho', max_length=255),
            preserve_default=False,
        ),
    ]
