# Generated by Django 3.2.6 on 2022-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
